sudo: required

before_install:
- sudo add-apt-repository ppa:texlive-backports/ppa -y
- sudo apt-get update
- sudo apt-get install biber

install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science pgf biblatex chktex latexmk

script:
- cd Report
- latexmk -pdf master.tex
# run linter on all tex files
- chktex $(find . -type f -name "*.tex")