addons:
  apt:
    packages:
    - texlive-full
    - pgf # needed for tikz
    - biblatex
    - chktex
    - latexmk

script:
# install biblatex-ieee package manually
- mkdir -p ~/texmf/tex/latex
- wget http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-ieee.zip -O biblatex-ieee.zip
- unzip biblatex-ieee.zip -d ~/texmf/tex/latex
- cd Report
- latexmk -pdf master.tex
# run linter on all tex files
- chktex $(find . -type f -name "*.tex")