addons:
  apt:
    packages:
    - texlive-full
    - pgf # needed for tikz
    - chktex
    - latexmk

script:
- cd Report
- latexmk -pdf master.tex
# run linter on all tex files
- chktex $(find . -type f -name "*.tex")